version: '3'
services:
    mongo:
        image: mongo:4.2
        container_name: mongo
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./mdb:/data/db
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        command: mongod 

