version: '3'
services:
    mysql:
        image: mysql:5.7 
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: sensetime
            MYSQL_DATABASE: industry
            TZ: Asia/Shanghai
        volumes:
            - ./data:/var/lib/mysql
            - ./conf/my.cnf:/etc/my.cnf
            - ./init:/docker-entrypoint-initdb.d/
        ports:
            - 3306:3306
