version: '3'
services:
    redis-master:
        image: redis:6.2
        container_name: redis-master
        restart: always
        ports:
        - 6379:6379
        volumes: 
        - ./data:/data
        - ./conf/redis.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
    redis-slave-0:
        image: redis:6.2
        container_name: redis-slave-0
        restart: always
        ports:
        - 6380:6379
        command: redis-server --masterauth sensetime --requirepass sensetime --slaveof redis-master 6379
    redis-slave-1:
        image: redis:6.2
        container_name: redis-slave-1
        restart: always
        ports:
        - 6381:6379
        command: --masterauth sensetime --requirepass sensetime --slaveof redis-master 6379
