version: "3"

services:
  zookeeper:
    image: zookeeper:3.4
    restart: always
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zk/data:/data
      - ./zk/datalog:/datalog
      - /etc/localtime:/etc/localtime:ro

  kafka-0:
    restart: always
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: kafka-0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181" # zk地址
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.152.208.13:9092 # Kafka广播地址及端口，也就是告诉客户端，使用什么地址和端口能连接到Kafka
      KAFKA_LISTENERS: PLAINTEXT://:9092 # Kafka启动所使用的的协议及端口
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_BROKER_ID: 1
    volumes:
      - ./kafka-0:/kafka
      - /etc/localtime:/etc/localtime:ro

