version: '3'
services:
    # data
    # 为了测试，删掉restart always选项
    redis-cluster-0:
        image: redis:6.2
        container_name: redis-cluster-0
        network_mode: host
        ports:
        - 6379:6379
        volumes: 
        - ./data/cluster-0:/data
        - ./conf/cluster-0.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
    redis-cluster-1:
        image: redis:6.2
        container_name: redis-cluster-1
        network_mode: host
        ports:
        - 6380:6380
        volumes: 
        - ./data/cluster-1:/data
        - ./conf/cluster-1.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
    redis-cluster-2:
        image: redis:6.2
        container_name: redis-cluster-2
        network_mode: host
        ports:
        - 6381:6381
        volumes: 
        - ./data/cluster-2:/data
        - ./conf/cluster-2.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
    redis-cluster-3:
        image: redis:6.2
        container_name: redis-cluster-3
        network_mode: host
        ports:
        - 6382:6382
        volumes: 
        - ./data/cluster-3:/data
        - ./conf/cluster-3.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
    redis-cluster-4:
        image: redis:6.2
        container_name: redis-cluster-4
        network_mode: host
        ports:
        - 6383:6383
        volumes: 
        - ./data/cluster-4:/data
        - ./conf/cluster-4.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
    redis-cluster-5:
        image: redis:6.2
        container_name: redis-cluster-5
        network_mode: host
        ports:
        - 6384:6384
        volumes: 
        - ./data/cluster-5:/data
        - ./conf/cluster-5.conf:/etc/redis/redis.conf
        command: redis-server /etc/redis/redis.conf
